### ISSUE TITLE
Update graphic

### ISSUE THREAD

**Issue by MakarovIlya944** [ekdrozdov/azino777#12]
Доработки графики
1.  Добавить отображение кэша каждого игрока   
2.  Изменение модели событий(на реактив сообщeния)
3.  Зеленые кружки сделать кнопками(чтобы у них было свойство Command)
*можно ещё туда плюсики поставить(но это от меня пожелание)*
4.  Забиндить все лейблы

**Comment by Erewer97** [comment]
f

**Comment by Erewer97** [comment]
1) Добавил
2) Пишу интерфейс
3) Сделал
