### ISSUE TITLE
Check data base

### ISSUE THREAD

**Issue by juliach98** [ekdrozdov/azino777#26]
1) Проверить, соответствует ли структура БД необходимым требованиям (можно ли с помощью нее полностью воссоздать игру). Реализованная БД близка к структуре БД из данного файла  (https://docs.google.com/document/d/1ldCUaW7Q4qLqGIfNuFLWvakCfl2wBDQwsrKMKxpuEbs/edit?usp=sharing).
2) Составить запросы, необходимые для AI.

**Comment by MakarovIlya944** [comment]
Хах, ты почти успела)

**Comment by MakarovIlya944** [comment]
на 5 минут раньше https://github.com/ekdrozdov/azino777/issues/25
@juliach98

**Comment by MakarovIlya944** [comment]
Ветка с базой данных https://github.com/ekdrozdov/azino777/tree/db-init

**Comment by ekdrozdov** [comment]
>Составить запросы, необходимые для AI. 

@juliach98 Можно пояснение к этому пункту?

**Comment by juliach98** [comment]
@ekdrozdov насколько я понимаю, нашей базой будет пользоваться ai, поэтому им бы нужно придумать необходимые им запросы

**Comment by ekdrozdov** [comment]
@MakarovIlya944 вам нужно придумать интерфейсы запросов к бд
