### ISSUE TITLE
Bind graphics

### ISSUE THREAD

**Issue by MakarovIlya944** [ekdrozdov/azino777#29]
Описать здесь список bindings     
1) view->model     
2) view->viewmodel

**Comment by juliach98** [comment]
money_in_little_bland -> _playerView.SmallBlind
money_in_big_bland -> _playerView.BigBlind
center_card1 -> _playerView.BoardCards[0]
center_card2 -> _playerView.BoardCards[1]
center_card3 -> _playerView.BoardCards[2]
center_card4 -> _playerView.BoardCards[3]
center_card5 -> _playerView.BoardCards[4]
money_in_main_bank -> _playerView.AllBank
textbox_number_of_money -> _playerView.CurrentBet
card1 -> _playerView.Players[CurPlayer].HandCards.Item1
card2 -> _playerView.Players[CurPlayer].HandCards.Item2
diller6 -> _playerView.Dealer
