### ISSUE TITLE
Сформулировать интерфейсы

### ISSUE THREAD

**Issue by ekdrozdov** [ekdrozdov/azino777#3]
Каждая команда должна разобраться, что именно она делает, в соответствии с этим продумать, что им понадобиться для реализации от модулей других команд и сформулировать соответствующие интерфейсы.
Далее каждая команда изучает все поступившие ей запросы, обсуждает и согласовывает их.

**Comment by ekdrozdov** [comment]
призываю всех @MakarovIlya944 @juliach98 @Anastassyaa @DiestoDeekey @ArtAku @Hangman97 @Erewer97 @katetap @lubovvit. Желательно утвердить как можно скорее, чтобы приступить уже непосредственно к разработке.

**Comment by desmoondWeiss** [comment]
Ребят, распишите, пожалуйста роли бригад и за что они отвечают. 
Шеньшин А.О.

**Comment by desmoondWeiss** [comment]
Держите в курсе, пожалуйста. Если нужна помощь - я на связи.
Шеньшин А.О.

**Comment by MakarovIlya944** [comment]
@ekdrozdov я считаю что мы уже можем приступать к реализации, пусть даже и не все интерфейсы сделали
