### ISSUE TITLE
Create requests for database

### ISSUE THREAD

**Issue by juliach98** [ekdrozdov/azino777#45]
AI необходимо придумать запросы для базы данных (https://docs.google.com/document/d/1ldCUaW7Q4qLqGIfNuFLWvakCfl2wBDQwsrKMKxpuEbs/edit?usp=sharing).

**Comment by MakarovIlya944** [comment]
Запрос нужен такой:     
если по простому то вернуть по заданному игроку по всем партиям массив значений вида (a,b,c,d) , где a-карты игрока, b-карты стола, c-ставка на конец, d-деньги игрока на начало партиям     
если по сложному то возвращать массив значений вида (e,f) e-сила комбинации от 1 до n, где n-кол-во всех комбинаций и 1 самая сильная комбинация. f-отношение ставки игрока к всем его деньгам
